In [9]:
import pandas as pd
df = pd.read_csv(r"C:\Users\Franc\Downloads\INmersiónDatosALura\Identificacion (Capitulo A)\Identificación (Capítulo A).csv",sep=";",encoding="latin-1")

In [10]:
df.head(15)

,DIRECTORIO,DPTO,MPIO,CLASE,COD_LOCALIDAD,NOMBRE_LOCALIDAD,COD_UPZ_GRUPO,NOMBRE_UPZ_GRUPO,ESTRATO2021,NOMBRE_ESTRATO,FEX_C
0,3004346.0,11,11001,1,3.0,Santa Fe,814.0,SANTA FE: Las Nieves + Sagrado Corazón,11001187,SANTA FE: Las Nieves + Sagrado Corazón,"13,2266692027239"
1,3004347.0,11,11001,1,14.0,Los Mártires,37.0,Santa Isabel,11001162,Santa Isabel,"17,8555889419101"
2,3004348.0,11,11001,1,3.0,Santa Fe,814.0,SANTA FE: Las Nieves + Sagrado Corazón,11001187,SANTA FE: Las Nieves + Sagrado Corazón,"10,0286103658331"
3,3004349.0,11,11001,1,1.0,Usaquén,803.0,USAQUÉN: Country Club + Santa Bárbara,11001176,USAQUÉN: Country Club + Santa Bárbara,"28,6502122142802"
4,3004350.0,11,11001,1,1.0,Usaquén,803.0,USAQUÉN: Country Club + Santa Bárbara,11001176,USAQUÉN: Country Club + Santa Bárbara,"24,4684068319009"
5,3004351.0,11,11001,1,2.0,Chapinero,816.0,CHAPINERO: Pardo Rubio + Chapinero,11001189,CHAPINERO: Pardo Rubio + Chapinero,"18,0625813452102"
6,3004352.0,11,11001,1,2.0,Chapinero,816.0,CHAPINERO: Pardo Rubio + Chapinero,11001189,CHAPINERO: Pardo Rubio + Chapinero,"32,5858068187955"
7,3004353.0,11,11001,1,9.0,Fontibón,110.0,Ciudad Salitre Occidental,11001115,Ciudad Salitre Occidental,"12,1448435131683"
8,3004354.0,11,11001,1,9.0,Fontibón,110.0,Ciudad Salitre Occidental,11001115,Ciudad Salitre Occidental,"17,5760700132957"
9,3004355.0,11,11001,1,1.0,Usaquén,13.0,Los Cedros,11001144,Los Cedros,"47,5444485649816"
10,3004356.0,11,11001,1,1.0,Usaquén,803.0,USAQUÉN: Country Club + Santa Bárbara,11001176,USAQUÉN: Country Club + Santa Bárbara,"26,6787228111482"
11,3004357.0,11,11001,1,1.0,Usaquén,13.0,Los Cedros,11001144,Los Cedros,"44,9787471512549"
12,3004358.0,11,11001,1,2.0,Chapinero,816.0,CHAPINERO: Pardo Rubio + Chapinero,11001189,CHAPINERO: Pardo Rubio + Chapinero,"32,5858068187955"
13,3004359.0,11,11001,1,1.0,Usaquén,13.0,Los Cedros,11001144,Los Cedros,"35,2275783935396"
14,3004360.0,11,11001,1,1.0,Usaquén,804.0,USAQUÉN: Paseo de Los Libertadores + La Uribe,11001177,USAQUÉN: Paseo de Los Libertadores + La Uribe,"18,6679574218312"

In [11]:
df.shape ##Número de datos

(106467, 11)

In [12]:
df = df.loc[df.MPIO == 11001] ##Tomamos sólo los datos que sean del Mpio 11001
df.shape ##Mostramos resultados son 20k datos menos

(86504, 11)

**Importar las bases de Datos necesarias**

In [18]:
dfB = pd.read_csv(r"C:\Users\Franc\Downloads\INmersiónDatosALura\archivos-dane\Datos de la vivenda y su entorno (Capítulo B).csv",sep=";",encoding="latin-1",low_memory=False)
dfC = pd.read_csv(r"C:\Users\Franc\Downloads\INmersiónDatosALura\archivos-dane\Condiciones habitacionales del hogar (Capítulo C).csv",sep=";",encoding="latin-1",low_memory=False)
dfE = pd.read_csv(r"C:\Users\Franc\Downloads\INmersiónDatosALura\archivos-dane\Composición del hogar y demografía (Capítulo E).csv",sep=";",encoding="latin-1",low_memory=False)
dfH = pd.read_csv(r"C:\Users\Franc\Downloads\INmersiónDatosALura\archivos-dane\Educación (Capítulo H).csv",sep=";",encoding="latin-1",low_memory=False)
dfL = pd.read_csv(r"C:\Users\Franc\Downloads\INmersiónDatosALura\archivos-dane\Percepción sobre las condiciones de vida y el desempeño institucional (Capítulo L).csv",sep=";",encoding="latin-1",low_memory=False)
dfK = pd.read_csv(r"C:\Users\Franc\Downloads\INmersiónDatosALura\archivos-dane\Fuerza de trabajo (Capítulo K).csv",sep=";",encoding="latin-1",low_memory=False)

In [19]:
dfG ##Impresión de los datos de una base, para ver sus datos

,DIRECTORIO,DIRECTORIO_HOG,DIRECTORIO_PER,SECUENCIA_P,ORDEN,NPCKP1,NPCKP2,NPCKP3,NPCKP4,NPCKP5,...,DES,FL,FFL,PET_DEFA,OCU_DEFA,DES_DEFA,INI_DEFA,PEA_DEFA,OINFORMAL,FEX_C
0,166238.0,1662381,16623811,1,1,4,2.0,2.0,2.0,2.0,...,0,0,1,1,0,0,1,0,NaN,"1,69849246231156"
1,166238.0,1662381,16623812,1,2,4,2.0,2.0,2.0,2.0,...,0,0,1,1,0,0,1,0,NaN,"1,69849246231156"
2,220102.0,2201021,22010214,1,4,3,2.0,2.0,2.0,2.0,...,0,0,0,1,0,0,1,0,NaN,"6,74441212899351"
3,220102.0,2201021,22010212,1,2,4,2.0,2.0,2.0,2.0,...,0,0,1,1,0,0,1,0,NaN,"6,74441212899351"
4,220102.0,2201021,22010211,1,1,1,NaN,NaN,NaN,NaN,...,0,1,0,1,1,0,0,1,1.0,"6,74441212899351"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260471,3006811.0,30068111,300681112,1,2,4,2.0,2.0,2.0,2.0,...,0,0,1,1,0,0,1,0,NaN,"15,0488158778498"
260472,3006811.0,30068111,300681111,1,1,4,2.0,2.0,2.0,2.0,...,0,0,1,1,0,0,1,0,NaN,"15,0488158778498"
260473,3006812.0,30068121,300681213,1,3,2,2.0,2.0,2.0,1.0,...,1,1,0,1,0,1,0,1,NaN,"16,3462870407952"
260474,3006812.0,30068121,300681212,1,2,2,2.0,2.0,2.0,1.0,...,1,1,0,1,0,1,0,1,NaN,"16,3462870407952"
260475,3006812.0,30068121,300681211,1,1,1,NaN,NaN,NaN,NaN,...,0,1,0,1,1,0,0,1,0.0,"16,3462870407952"

In [20]:
Datos_DANE = pd.merge(df, dfB, on = "DIRECTORIO",how = "left") ##Unimos las tablas a la Izquierda(Left Join) para conservar
Datos_DANE.shape                                               ## la información de las encuestas.

(86504, 73)

In [21]:
Datos_DANE = pd.merge(Datos_DANE, dfC, on = "DIRECTORIO",how = "left") ##Unimos las tablas a la Izquierda(Left Join) para conservar
Datos_DANE.shape                                               ## la información de las encuestas.

(87061, 214)

In [22]:
Datos_DANE = pd.merge(Datos_DANE, dfE, on = "DIRECTORIO",how = "left") ##Unimos las tablas a la Izquierda(Left Join) para conservar
Datos_DANE.shape

C:\Users\Franc\AppData\Local\Temp\ipykernel_34372\1967157183.py:1: FutureWarning: Passing 'suffixes' which cause duplicate columns {'FEX_C_x'} in the result is deprecated and will raise a MergeError in a future version.
  Datos_DANE = pd.merge(Datos_DANE, dfE, on = "DIRECTORIO",how = "left") ##Unimos las tablas a la Izquierda(Left Join) para conservar

(238559, 281)

In [24]:
Datos_DANE.info() ##Revisamos la información que contienen dentro del DataFrame DANE

<class 'pandas.core.frame.DataFrame'>
Int64Index: 238559 entries, 0 to 238558
Columns: 281 entries, DIRECTORIO to FEX_C_y
dtypes: float64(140), int64(126), object(15)
memory usage: 513.3+ MB

# Desafio 3
**Dar una vista a la base del DANE, entender estas variables conceptuales para entender mejor el contexto de esta base.**

**Organizar tu Notebook, para que el poyecto quede mejor presentado.**

In [37]:
Datos_DANE.columns.values[:281] ##Observamos las variables involucradas en este nuevo DataFrame

array(['DIRECTORIO', 'DPTO', 'MPIO', 'CLASE', 'COD_LOCALIDAD',
       'NOMBRE_LOCALIDAD', 'COD_UPZ_GRUPO', 'NOMBRE_UPZ_GRUPO',
       'ESTRATO2021', 'NOMBRE_ESTRATO', 'FEX_C_x', 'NVCBP1', 'NVCBP2',
       'NVCBP3', 'NVCBP4', 'NVCBP5', 'NVCBP6', 'NVCBP7', 'NVCBP8A',
       'NVCBP8B', 'NVCBP8C', 'NVCBP8D', 'NVCBP8E', 'NVCBP8F', 'NVCBP8G',
       'NVCBP8H', 'NVCBP8I', 'NVCBP8J', 'NVCBP9', 'NVCBP9A1', 'NVCBP9A2',
       'NVCBP9A3', 'NVCBP9A4', 'NVCBP10', 'NVCBP11A', 'NVCBP11AA',
       'NVCBP11B', 'NVCBP11C', 'NVCBP11D', 'NVCBP11DA', 'NVCBP12',
       'NVCBP13', 'NVCBP14A', 'NVCBP14B', 'NVCBP14C', 'NVCBP14D',
       'NVCBP14E', 'NVCBP14L', 'NVCBP14F', 'NVCBP14G', 'NVCBP14H',
       'NVCBP14I', 'NVCBP14J', 'NVCBP14K', 'NVCBP15A', 'NVCBP15B',
       'NVCBP15C', 'NVCBP15D', 'NVCBP15E', 'NVCBP15F', 'NVCBP15G',
       'NVCBP15H', 'NVCBP15I', 'NVCBP15J', 'NVCBP15K', 'NVCBP15L',
       'NVCBP15M', 'NVCBP16A1', 'NVCBP16A2', 'NVCBP16A3', 'NVCBP16A4',
       'NVCBP16', 'FEX_C_y', 'DIRECTORIO_HOG_x', 'SECUENCIA_P_x',
       'NHCCP1', 'NHCCP2', 'NHCCP3', 'NHCCP4A', 'NHCCP4B', 'NHCCP4C',
       'NHCCP4D', 'NHCCP4E', 'NHCCP5', 'NHCCP6', 'NHCCP7', 'NHCCP8_1',
       'NHCCP8_2', 'NHCCP8_3', 'NHCCP8_4', 'NHCCP8_5', 'NHCCP8_6',
       'NHCCP8_7', 'NHCCP8_8', 'NHCCP8_9', 'NHCCP8_10', 'NHCCP9',
       'NHCCP10', 'NHCCP10A', 'NHCCP10B', 'NHCCP10C', 'NHCCP10D',
       'NHCCP10E', 'NHCCP11', 'NHCCP11A', 'NHCCP12', 'NHCCP13A',
       'NHCCP13B', 'NHCCP13C', 'NHCCP13D', 'NHCCP13E', 'NHCCP13F',
       'NHCCP13G', 'NHCCP13H', 'NHCCP13I', 'NHCCP13J', 'NHCCP14',
       'NHCCP14A', 'NHCCP15', 'NHCCP15A', 'NHCCPCTRL2', 'NHCCP19',
       'NHCCP19A', 'NHCCP20', 'NHCCP22A', 'NHCCP22B', 'NHCCP22C',
       'NHCCP22D', 'NHCCP22E', 'NHCCP23', 'NHCCP24', 'NHCCP25', 'NHCCP26',
       'NHCCP26A', 'NHCCP27', 'NHCCP28', 'NHCCP28A', 'NHCCP29',
       'NHCCP29A', 'NHCCP31', 'NHCCP32', 'NHCCP33', 'NHCCP34', 'NHCCP35',
       'NHCCP35A', 'NHCCP36A', 'NHCCP36B', 'NHCCP36C', 'NHCCP37',
       'NHCCP38', 'NHCCP38AA', 'NHCCP38AB', 'NHCCP38AC', 'NHCCP38AD',
       'NHCCP38AF', 'NHCCP38AG', 'NHCCP38B', 'NHCCP39A', 'NHCCP39B',
       'NHCCP393', 'NHCCP39C', 'NHCCP39D', 'NHCCP39E', 'NHCCP39F',
       'NHCCP39G', 'NHCCP399', 'NHCCP40A', 'NHCCP40B', 'NHCCP40C',
       'NHCCP40D', 'NHCCP40E', 'NHCCP40F', 'NHCCP40G', 'NHCCP40H',
       'NHCCP40I', 'NHCCP40J', 'NHCCP40K', 'NHCCP40L', 'NHCCP40M',
       'NHCCP40N', 'NHCCP40O', 'NHCCP40P', 'NHCCP41', 'NHCCP41A',
       'NHCCP41B', 'NHCCP42', 'NHCCP42A', 'NHCCP44', 'NHCCP44A',
       'NHCCP44B', 'NHCCP45', 'NHCCP45A', 'NHCCP45B', 'NHCCP41_A',
       'NHCCP41_B', 'NHCCP46A', 'NHCCP46B', 'NHCCP46C', 'NHCCP46D',
       'NHCCP46E', 'NHCCP46F', 'NHCCP46G', 'NHCCP46H', 'NHCCP46I',
       'NHCCP46J', 'NHCCP46K', 'NHCCP46L', 'NHCCP46M', 'NHCCP47A',
       'NHCCP47A1', 'NHCCP47B', 'NHCCP47B1', 'NHCCP47C', 'FEX_C_x',
       'DIRECTORIO_HOG_y', 'DIRECTORIO_PER', 'SECUENCIA_P_y', 'ORDEN',
       'NPCEP4', 'NPCEP_5', 'NPCEP5', 'SEXO', 'NPCEP6', 'NPCEP7',
       'NPCEP8', 'NPCEP8A', 'NPCEP9', 'NPCEP9A', 'NPCEP9B', 'NPCEP9C',
       'NPCEP10', 'NPCEP11A', 'NPCEP11AA', 'NPCEP11AB', 'NPCEP11D',
       'NPCEP11', 'NPCEP13', 'NPCEP13A', 'NPCEP13B', 'NPCEP13D',
       'NPCEP14', 'NPCEP16_1', 'NPCEP16A_1', 'NPCEP16B_1', 'NPCEP16D_1',
       'NPCEP17_1', 'NPCEP15', 'NPCEP16_1A', 'NPCEP16_2A', 'NPCEP16_3A',
       'NPCEP16_4A', 'NPCEP16_5A', 'NPCEP16_6A', 'NPCEP16_7A',
       'NPCEP16_8A', 'NPCEP16A', 'NPCEP16AA', 'NPCEP16AB', 'NPCEP16B',
       'NPCEP21A_1', 'NPCEP21A_2M', 'NPCEP21B_1', 'NPCEP21B_2',
       'NPCEP21B_3', 'NPCEP21B_4', 'NPCEP21B_5', 'NPCEP21C_1', 'NPCEP17',
       'NPCEP21', 'NPCEP21A', 'NPCEP22', 'NPCEP22A', 'NPCEP24',
       'NPCEP24A', 'NPCEP25', 'NPCEP25A', 'NPCEP27', 'NPCEP26', 'NPCEP29',
       'NPCEP29A', 'FEX_C_y'], dtype=object)

In [44]:
Datos_DANE.head(1) ##Ahora hay que leer la documentación para comprender el contexto de cada variable(Columna)

,DIRECTORIO,DPTO,MPIO,CLASE,COD_LOCALIDAD,NOMBRE_LOCALIDAD,COD_UPZ_GRUPO,NOMBRE_UPZ_GRUPO,ESTRATO2021,NOMBRE_ESTRATO,...,NPCEP22A,NPCEP24,NPCEP24A,NPCEP25,NPCEP25A,NPCEP27,NPCEP26,NPCEP29,NPCEP29A,FEX_C_y
0,3004346.0,11,11001,1,3.0,Santa Fe,814.0,SANTA FE: Las Nieves + Sagrado Corazón,11001187,SANTA FE: Las Nieves + Sagrado Corazón,...,2.0,2,NaN,1.0,5.0,1.0,1.0,NaN,NaN,"13,2266692027239"